### ISSUE TITLE
Releases v2.0.4 &  v2.0.5 were not added to Ansible Galaxy

### ISSUE THREAD

**Issue by dekabrist89** [Oefenweb/ansible-supervisor#42]
I am using requirements.yml file with this cool supervisor role:
```
---
- src: tersmitten.supervisor
  version: v2.0.3
```
But i can't upgrade it to a newer version because there is no such version on Ansible Galaxy - https://galaxy.ansible.com/tersmitten/supervisor/
That is why `ansible-galaxy install -r requirements.yml --force` return me this error: "The specified version (v2.0.4) of tersmitten.supervisor was not found in the list of available versions"
Please add it when you will have some free time! Thanks!

**Comment by tersmitten** [comment]
I'll have a look

**Comment by tersmitten** [comment]
https://galaxy.ansible.com/tersmitten/supervisor/ lists them as released

**Comment by tersmitten** [comment]
Can you give it another try?

**Comment by dekabrist89** [comment]
Really strange, there were no these 2 versions in Ansible Galaxy yesterday, but now all looks and works good! Thank you for a quick response. Closing this issue
