### ISSUE TITLE
minfds does not work in Ubuntu

### ISSUE THREAD

**Issue by praisebob** [Oefenweb/ansible-supervisor#49]
Setting minfds value in supervisor.conf does not work in Ubuntu 16.04 (possibly other versions too) if the value is larger than default value of 4096.

We are running supervisor as non-privileged user with custom paths for directories and sockets, but this does not seem to be of relevance to the issue as otherwise the service runs normally. Appropriate open file limits for user and system are raised sufficiently and supervisor version installed from official Ubuntu package works as expected.

The issue seems to be that the version installed with pip when started with systemd does not have some kind of privileges to raise the open file limit for supervisor itself and it's subprocesses. And it fails with error message like this for example:
`Error: The minimum number of file descriptors required to run this process is 6000 as per the "minfds" command-line argument or config file setting. The current environment will only allow you to open 6000 file descriptors.`

The actual value can be anything more than 4096 and I am using 6000 in the example.

Hopefully something can be done to solve this.

Thank you for your consideration.

**Comment by tersmitten** [comment]
How do you set the open file limit?

**Comment by praisebob** [comment]
System limit is set via sysclt `fs.file-max` variable that is several times larger than value set in supervisord config. Also there are entries in `/etc/security/limits.conf` file for `root`, `*` and `foobar` user that sets soft and hard limits that have values smaller than system limit but still multiple times larger than value in supervisord config. I can verify they do apply by `su`'ing to the user in question and using `ulimit -Hn` command. And rebooting the system after I change any of these settings just in case.

Also I forgot to mention that if I run supervisor from interactive shell (after `su` to user account) it works as expected and I can verify that the correct limit is applied by using `cat /proc/{PID}/limits` command for supervisord and subtasks. The issue seems to be supervisord unit related. And I have mentioned that using supervisor supplied via official package requires none of this - an entry in `supervisord.conf` is sufficient (up to a limit I guess).

I have also resolved to adding `session required pam_limits.so` entries to `common-session` and `common-session-noninteractive` pam files in `/etc/pam.d/` and rebooting the system afterwards of course. Did not help and is not really required for it to work.

**Comment by tersmitten** [comment]
I think you need a `systemd` override. This is something we use for `mysqld`:

```
# cat /etc/systemd/system/mysql.service.d/limits.conf 
[Service]
LimitNOFILE=infinity
LimitMEMLOCK=infinity
```

**Comment by praisebob** [comment]
It works. 

The minfds value in `supervisord.conf` is ignored in this case and the value from `limits.conf` is taken. I just wonder how supervisor from official Ubuntu package manages to work without it.

If I'll manage to find any more information about that I will post a reply here.

Consider it solved.

Thank you.
