### ISSUE TITLE
Support for Supervisor 4 on Python 3

### ISSUE THREAD

**Issue by kangas** [Oefenweb/ansible-supervisor#50]
Currently this role is hardwired to use pip2. Python 2.7 is EOL January 2020.

Is there interest in updating this role to support Supervisor 4 with Python 3.4+? A basic patch to convert to python3 is simple, but I assume you'll want to be backwards compatible.

Do you have a preference on how you want to support python2/3?

https://github.com/Supervisor/supervisor/issues/1240
https://github.com/Supervisor/supervisor/blob/4.0.0/CHANGES.txt#L4-L38

**Comment by tersmitten** [comment]
Fixed in #51
